module.exports = {};

module.exports.data = [{
  position: penjaga gawang,
  dribbling: ['good', 'medium', 'bad'],
  finishing: ['good', 'medium', 'bad'],
  crossing: ['good', 'medium', 'bad'],
  heading: ['good', 'medium', 'bad'],
  marking: ['good', 'medium', 'bad'],
  passing: ['good', 'medium', 'bad'],
  tackling: ['good', 'medium', 'bad'],
  agility: ['good', 'medium', 'bad'],
  balance: ['good', 'medium', 'bad'],
  speed: ['good', 'medium', 'bad'],
  stamina: ['good', 'medium', 'bad'],
  strength: ['good', 'medium', 'bad'],
  vision: ['good'],
  anticipation: ['good'],
  goalkeeping: ['good']
}, {
  position: bek tengah,
  dribbling: ['good', 'medium', 'bad'],
  finishing: ['good', 'medium', 'bad'],
  crossing: ['good', 'medium', 'bad'],
  heading: ['good', 'medium'],
  marking: ['good', 'medium'],
  passing: ['good', 'medium'],
  tackling: ['good'],
  agility: ['good', 'medium', 'bad'],
  balance: ['good'],
  speed: ['good', 'medium', 'bad'],
  stamina: ['good', 'medium', 'bad'],
  strength: ['good'],
  vision: ['good', 'medium', 'bad'],
  anticipation: ['good'],
  goalkeeping: ['good', 'medium', 'bad']
}, {
  position: bek sayap,
  dribbling: ['good', 'medium'],
  finishing: ['good', 'medium', 'bad'],
  crossing: ['good'],
  heading: ['good', 'medium', 'bad'],
  marking: ['good', 'medium'],
  passing: ['good', 'medium'],
  tackling: ['good', 'medium'],
  agility: ['good', 'medium'],
  balance: ['good', 'medium'],
  speed: ['good'],
  stamina: ['good'],
  strength: ['good', 'medium', 'bad'],
  vision: ['good', 'medium', 'bad'],
  anticipation: ['good', 'medium'],
  goalkeeping: ['good', 'medium', 'bad']
}, {
  position: gelandang bertahan,
  dribbling: ['good', 'medium', 'bad'],
  finishing: ['good', 'medium', 'bad'],
  crossing: ['good', 'medium', 'bad'],
  heading: ['good', 'medium', 'bad'],
  marking: ['good', 'medium', 'bad'],
  passing: ['good'],
  tackling: ['good', 'medium'],
  agility: ['good', 'medium'],
  balance: ['good'],
  speed: ['good', 'medium', 'bad'],
  stamina: ['good', 'medium', 'bad'],
  strength: ['good'],
  vision: ['good'],
  anticipation: ['good', 'medium', 'bad'],
  goalkeeping: ['good', 'medium', 'bad']
}, {
  position: gelandang sayap,
  dribbling: ['good'],
  finishing: ['good', 'medium', 'bad'],
  crossing: ['good'],
  heading: ['good', 'medium', 'bad'],
  marking: ['good', 'medium', 'bad'],
  passing: ['good', 'medium'],
  tackling: ['good', 'medium', 'bad'],
  agility: ['good'],
  balance: ['good', 'medium'],
  speed: ['good'],
  stamina: ['good'],
  strength: ['good', 'medium', 'bad'],
  vision: ['good', 'medium', 'bad'],
  anticipation: ['good', 'medium', 'bad'],
  goalkeeping: ['good', 'medium', 'bad']
}, {
  position: gelandang serang,
  dribbling: ['good', 'medium'],
  finishing: ['good', 'medium'],
  crossing: ['good', 'medium', 'bad'],
  heading: ['good', 'medium', 'bad'],
  marking: ['good', 'medium', 'bad'],
  passing: ['good'],
  tackling: ['good', 'medium', 'bad'],
  agility: ['good'],
  balance: ['good', 'medium'],
  speed: ['good', 'medium', 'bad'],
  stamina: ['good', 'medium', 'bad'],
  strength: ['good', 'medium', 'bad'],
  vision: ['good', 'medium'],
  anticipation: ['good', 'medium', 'bad'],
  goalkeeping: ['good', 'medium', 'bad']
}, {
  position: penyerang,
  dribbling: ['good', 'medium'],
  finishing: ['good'],
  crossing: ['good', 'medium', 'bad'],
  heading: ['good'],
  marking: ['good', 'medium', 'bad'],
  passing: ['good', 'medium', 'bad'],
  tackling: ['good', 'medium', 'bad'],
  agility: ['good', 'medium'],
  balance: ['good', 'medium', 'bad'],
  speed: ['good', 'medium', 'bad'],
  stamina: ['good', 'medium', 'bad'],
  strength: ['good', 'medium'],
  vision: ['good', 'medium', 'bad'],
  anticipation: ['good', 'medium', 'bad'],
  goalkeeping: ['good', 'medium', 'bad']
}, {
  position: latihan lagi,
  dribbling: ['good', 'medium', 'bad'],
  finishing: ['good', 'medium', 'bad'],
  crossing: ['good', 'medium', 'bad'],
  heading: ['good', 'medium', 'bad'],
  marking: ['good', 'medium', 'bad'],
  passing: ['good', 'medium', 'bad'],
  tackling: ['good', 'medium', 'bad'],
  agility: ['good', 'medium', 'bad'],
  balance: ['good', 'medium', 'bad'],
  speed: ['good', 'medium', 'bad'],
  stamina: ['good', 'medium', 'bad'],
  strength: ['good', 'medium', 'bad'],
  vision: ['good', 'medium', 'bad'],
  anticipation: ['good', 'medium', 'bad'],
  goalkeeping: ['good', 'medium', 'bad']
}];